package com.zarkonnen.cyberpunk;

import static com.zarkonnen.cyberpunk.TileType.*;
import static com.zarkonnen.cyberpunk.ItemType.*;

public enum ItemSpawner {
	MACHP(MACHINE_ROOM, MACHINE_PARTS, 20, 5),
	SWC(SWEATSHOP, DESIGNER_CLOTHES, 10, 8),
	DRGU(DRUG_LAB, UPPERS, 50, 8),
	DRGD(DRUG_LAB, DOWNERS, 50, 8),
	DRGUX(DRUG_LAB, EXPERIMENTAL_UPPERS, 80, 30, 3),
	DRGDX(DRUG_LAB, EXPERIMENTAL_DOWNERS, 80, 30, 3),
	DRGCH(DRUG_LAB, CHEMICALS, 20, 20),
	VFF(V_FARM, VEGETABLES, 10, 20),
	HFF(ROOFTOP_FARM, VEGETABLES, 30, 10),
	STRAG(STORE_ROOM, ANGLE_GRINDER, 40, 30, 1),
	STRCH(STORE_ROOM, CHEMICALS, 10, 60, 10),
	STRDC(STORE_ROOM, DESIGNER_CLOTHES, 20, 10, 10),
	STRMP(STORE_ROOM, MACHINE_PARTS, 30, 30, 10),
	STRRAT(STORE_ROOM, RATIONS, 50, 30, 5),
	STRSN(STORE_ROOM, SNACKS, 30, 30, 10),
	STRRAM(STORE_ROOM, RAM, 30, 30, 5),
	WHAG(WAREHOUSE_BARGE, ANGLE_GRINDER, 30, 30, 1),
	WHCH(WAREHOUSE_BARGE, CHEMICALS, 10, 30, 10),
	WHDC(WAREHOUSE_BARGE, DESIGNER_CLOTHES, 20, 10, 10),
	WHMP(WAREHOUSE_BARGE, MACHINE_PARTS, 20, 30, 10),
	WHRAT(WAREHOUSE_BARGE, RATIONS, 50, 30, 5),
	WHSN(WAREHOUSE_BARGE, SNACKS, 30, 30, 10),
	WHRAM(WAREHOUSE_BARGE, VEGETABLES, 30, 30, 5),
	WHPIS(WAREHOUSE_BARGE, PISTOL, 60, 30, 5),
	OFR(OFFICE, RAM, 20, 10),
	OFCPU(OFFICE, CPUS, 20, 10),
	OFDAT(OFFICE, VALUABLE_DATA, 60, 3),
	OFQC(OFFICE, QUANTUM_CORE, 80, 20, 1),
	OFMP(OFFICE, MACHINE_PARTS, 10, 30, 5),
	GUNR(GUN_SHOP, ASSAULT_RIFLE, 30, 2),
	GUNP(GUN_SHOP, PISTOL, 20, 4),
	GUNTR(GUN_SHOP, TRANQ_DART, 40, 30, 3),
	GUNTRB(GUN_SHOP, TRANQ_BUG, 60, 10, 2),
	JEW(JEWELLERY_SHOP, JEWELLERY, 20, 5),
	ARTS(ART_GALLERY, ART, 10, 2),
	CLOTH(CLOTHES_SHOP, DESIGNER_CLOTHES, 10, 8),
	SUIT(CLOTHES_SHOP, SHARP_SUIT, 10, 30, 3),
	MIRRS(CLOTHES_SHOP, MIRRORSHADES, 20, 50, 2),
	GRIND(CLINIC, GRINDER_TOOLS, 40, 2),
	MEDS(CLINIC, MEDICAL_SUPPLIES, 60, 10),
	CMP(CLINIC, MACHINE_PARTS, 30, 30, 5),
	CI(CLINIC, MEDICAL_HELPER_IMPLANT, 70, 30, 1),
	CI2(CLINIC, STRENGTH_ENHANCEMENT, 70, 30, 1),
	CEYES(CLINIC, MULTIWAVE_EYES, 70, 30, 1),
	HWAG(HARDWARE_SHOP, ANGLE_GRINDER, 20, 50, 2),
	HWMP(HARDWARE_SHOP, MACHINE_PARTS, 20, 10),
	HWB(HARDWARE_SHOP, BUG, 50, 30, 2),
	HWWT(HARDWARE_SHOP, WIRETAP, 50, 20, 2),
	HWRWT(HARDWARE_SHOP, REMOTE_WIRETAP, 70, 20, 1),
	BRD(BACK_ROOM, VALUABLE_DATA, 70, 30, 1),
	BRT(BACK_ROOM, AMATEUR_SEX_VID, 20, 20, 3),
	BRE(BACK_ROOM, BOOTLEG_ENTERTAINMENT, 10, 60, 9),
	APDRG(APARTMENT, DOWNERS, 60, 50, 3),
	APFOOD(APARTMENT, VEGETABLES, 10, 80, 3),
	APSN(APARTMENT, SNACKS, 20, 60, 3),
	APGUN(APARTMENT, PISTOL, 80, 30, 1),
	APGRN(APARTMENT, GRINDER_TOOLS, 20, 60, 1),
	SLUMDRG(ROOFTOP_SLUM, DOWNERS, 90, 70, 2),
	SLUMFD(ROOFTOP_SLUM, VEGETABLES, 20, 70, 2),
	SLUMSP(ROOFTOP_SLUM, SPEAR, 10, 50, 1),
	PENDRG(PENTHOUSE, UPPERS, 20, 60, 3),
	PENEX(PENTHOUSE, EXPERIMENTAL_UPPERS, 30, 30, 3),
	PENEXD(PENTHOUSE, EXPERIMENTAL_DOWNERS, 30, 30, 3),
	PENDATA(PENTHOUSE, VALUABLE_DATA, 60, 80, 3),
	SERVDATA(SERVER_ROOM, VALUABLE_DATA, 70, 100, 3),
	SERVR(SERVER_ROOM, RAM, 10, 12),
	SERVCPU(SERVER_ROOM, CPUS, 10, 12),
	SERVQC(SERVER_ROOM, QUANTUM_CORE, 50, 30, 1),
	SERVMP(SERVER_ROOM, MACHINE_PARTS, 10, 5),
	;
	
	public final TileType tile;
	public final ItemType item;
	public final int hiding;
	public final int p;
	public final int q;

	private ItemSpawner(TileType tile, ItemType item, int hiding, int q) {
		this.tile = tile;
		this.item = item;
		this.hiding = hiding;
		this.p = 100;
		this.q = q;
	}
	
	private ItemSpawner(TileType tile, ItemType item, int hiding, int p, int q) {
		this.tile = tile;
		this.item = item;
		this.hiding = hiding;
		this.p = p;
		this.q = q;
	}
	
	public void install(WorldMap wm) {
		for (Tile t : wm.tilesOfType(tile)) {
			if (wm.r.nextInt(100) < p) {
				for (int i = 0; i < q; i++) {
					Item it = new Item(item);
					if (item.maxAge > 0) {
						it.age = wm.r.nextInt(item.maxAge / 2);
					}
					t.hiddenItems.add(new Tile.HiddenItem((int) ((0.25 + wm.r.nextDouble() * 1.5) * hiding), it));
				}
			}
		}
	}
	
	public static void installAll(WorldMap wm) {
		for (ItemSpawner is : ItemSpawner.values()) {
			is.install(wm);
		}
	}
}
